### ISSUE TITLE
Move docstrings style towards a napoleon Google style to be rendered with ReadTheDocs

### ISSUE THREAD

**Issue by abenassi** [thomasballinger/rlundo#27]
http://sphinxcontrib-napoleon.readthedocs.org/en/latest/index.html

Docstrings should be rewritten following a style compatible with automatic ReadTheDocs rendering for documentation.

**Comment by abenassi** [comment]
Google style example by napoleon

http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html#example-google

**Comment by thomasballinger** [comment]
:+1:

**Comment by thomasballinger** [comment]
Not a priority :)
