### ISSUE TITLE
Deal with ANSI escape sequences in count lines

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/rlundo#4]
ANSI color sequences make rewrite.py think the cursor has move down more lines than it actually has. These should be filtered out.

Eventually we may need to switch to a terminal emulator for this, so tests for this behavior are also really important in fixing this - they might be the portion of the code that lives on.

**Comment by thomasballinger** [comment]
This is happening now thanks to work by @abenassi - thanks!

**Comment by abenassi** [comment]
:-)
